### ISSUE TITLE
REST API -  IM list full name

### ISSUE THREAD

**Issue by michalvadak** [RocketChat/developer-docs#60]
Is it possible to send users full name on /im.list endpoint?

**Comment by sampaiodiego** [comment]
by looking the code: 

https://github.com/RocketChat/Rocket.Chat/blob/607d42db9bf42a7e25f3fa520d989efdbe5d8eca/app/api/server/v1/im.js#L304

it would require additional development, since we're just returning room objects, and user's names are stored on `users` collection.

I'm closing this issue since it is more a feature request for rocket.chat, than an issue with the documentation. Feel free to open an issue on https://github.com/RocketChat/Rocket.Chat though. thx
